version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=health_check
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    expose:
      - 3306

  backend:
    build:
      context: ../be
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - REACT_APP_HOST=http://14.225.254.232
      # - DB_HOST=host.docker.internal
    ports:
      - 6969:6969

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../fe/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
